version: '3.8'

services:
  ai-blog-generator:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s