const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 3000;

const server = http.createServer((req, res) => {
  const url = req.url;
  
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  if (url === '/') {
    const html = fs.readFileSync('./client/index.html', 'utf8');
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(html);
  } else if (url === '/style.css') {
    const css = fs.readFileSync('./client/style.css', 'utf8');
    res.writeHead(200, { 'Content-Type': 'text/css' });
    res.end(css);
  } else if (url === '/script.js') {
    const js = fs.readFileSync('./client/script.js', 'utf8');
    res.writeHead(200, { 'Content-Type': 'application/javascript' });
    res.end(js);
  } else if (url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end('{"status":"OK"}');
  } else if (url === '/generate' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', () => {
      const data = JSON.parse(body);
      const content = `Hey there! Let's dive into ${data.keywords}. This is a sample blog post generated in ${data.tone} tone with ${data.length} length. The content would normally be generated by AI, but this is a working demo version.`;
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({
        success: true,
        content: content,
        metadata: data
      }));
    });
  } else if (url === '/generate-pdf' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', () => {
      const data = JSON.parse(body);
      const html = `<!DOCTYPE html><html><head><title>Blog Post</title><style>body{font-family:Arial;margin:40px;line-height:1.6}</style></head><body><h1>AI Generated Blog Post</h1><p>${data.content}</p></body></html>`;
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ html, fallback: true }));
    });
  } else {
    res.writeHead(404);
    res.end('Not found');
  }
});

server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    console.log(`Port ${PORT} is in use. Try: netstat -ano | findstr :${PORT}`);
  } else {
    console.log('Server error:', err.message);
  }
});